-- Reconstructed Jobsite Finder V1 schema baseline for local disposable testing.
-- Source: schema-only dump jobsite-schema-only-20260807-191320.sql.
-- This file contains no table data and must not be used as a production data export.
-- Historical migrations 001-033 remain authoritative for all later changes.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text default 'worker',
  created_at timestamptz default now()
);

create table if not exists public.worker_profiles (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  trade text,
  experience_years integer,
  city text,
  resume_url text,
  bio text,
  created_at timestamptz default now()
);

create unique index if not exists worker_profiles_profile_id_uidx
  on public.worker_profiles(profile_id);

create table if not exists public.company_profiles (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  company_name text not null,
  company_type text not null default 'gc',
  description text,
  trades_hired text,
  verified boolean default false,
  created_at timestamptz default now(),
  is_public boolean default true
);

create unique index if not exists company_profiles_profile_id_uidx
  on public.company_profiles(profile_id);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  project_name text,
  project_type text,
  sector text,
  city text,
  region text,
  province text default 'Alberta',
  address text,
  latitude double precision,
  longitude double precision,
  stage text,
  status text,
  estimated_value numeric,
  owner text,
  general_contractor text,
  start_date text,
  end_date text,
  description text,
  source_url text,
  is_active boolean default true,
  is_public_project boolean default true,
  is_featured boolean default false,
  project_status_type text default 'unverified',
  created_at timestamptz default now(),
  claimed_by_company_id bigint
);

create table if not exists public.jobsites (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  latitude double precision,
  longitude double precision,
  address text,
  city text,
  province text default 'Alberta',
  created_at timestamptz default now()
);

create table if not exists public.job_posts (
  id bigint generated by default as identity primary key,
  jobsite_id bigint references public.jobsites(id) on delete cascade,
  company_profile_id bigint references public.company_profiles(id) on delete set null,
  title text not null,
  trade text,
  employment_type text,
  schedule text,
  pay_range text,
  description text,
  requirements text,
  status text default 'open',
  created_at timestamptz default now(),
  expires_at date,
  project_id bigint references public.projects(id) on delete cascade
);

create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  job_post_id bigint not null references public.job_posts(id) on delete cascade,
  worker_profile_id bigint not null references public.worker_profiles(id) on delete cascade,
  resume_url text,
  message text,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists public.project_claims (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  company_profile_id bigint not null references public.company_profiles(id) on delete cascade,
  claim_type text not null default 'gc',
  status text not null default 'pending',
  notes text,
  created_at timestamptz default now()
);

create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select coalesce(
    (auth.jwt() -> 'user_metadata' ->> 'role'),
    (
      select profiles.role
      from public.profiles
      where profiles.id = auth.uid()
    ),
    'anon'
  );
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

alter table public.profiles enable row level security;
alter table public.worker_profiles enable row level security;
alter table public.company_profiles enable row level security;
alter table public.projects enable row level security;
alter table public.jobsites enable row level security;
alter table public.job_posts enable row level security;
alter table public.applications enable row level security;
alter table public.project_claims enable row level security;

create policy "profiles self read" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles self insert" on public.profiles
  for insert with check (auth.uid() = id);

create policy "profiles self update" on public.profiles
  for update using (auth.uid() = id);

create policy "worker_profiles_select_own" on public.worker_profiles
  for select using (auth.uid() = profile_id);

create policy "worker_profiles_insert_own" on public.worker_profiles
  for insert with check (auth.uid() = profile_id);

create policy "worker_profiles_update_own" on public.worker_profiles
  for update using (auth.uid() = profile_id) with check (auth.uid() = profile_id);

create policy "company_profiles_select_all" on public.company_profiles
  for select using (true);

create policy "company_profiles_insert_own" on public.company_profiles
  for insert with check (auth.uid() = profile_id);

create policy "company_profiles_update_own" on public.company_profiles
  for update using (auth.uid() = profile_id) with check (auth.uid() = profile_id);

create policy "projects visible to everyone" on public.projects
  for select to authenticated, anon using (true);

create policy "jobsites authed read all" on public.jobsites
  for select to authenticated using (true);

create policy "job_posts_select_public" on public.job_posts
  for select using (status = 'open');

create policy "applications_select_own" on public.applications
  for select using (
    worker_profile_id in (
      select id from public.worker_profiles where profile_id = auth.uid()
    )
  );

create policy "applications_insert_own" on public.applications
  for insert with check (
    worker_profile_id in (
      select id from public.worker_profiles where profile_id = auth.uid()
    )
  );

create policy "project_claims_select_own" on public.project_claims
  for select using (
    company_profile_id in (
      select id from public.company_profiles where profile_id = auth.uid()
    )
  );
