export const googleMapsDarkStyle = [
  { elementType: 'geometry', stylers: [{ color: '#24272b' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#c9d1d9' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#17191d' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#facc15' }, { lightness: -45 }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill', stylers: [{ color: '#e5e7eb' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#f4d46a' }] },
  { featureType: 'administrative.province', elementType: 'labels.text.fill', stylers: [{ color: '#d1d5db' }] },
  { featureType: 'landscape.natural', elementType: 'geometry', stylers: [{ color: '#20262a' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#252a2e' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#98a2ad' }] },
  { featureType: 'poi.business', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#1f3229' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#93c5a5' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#3c4147' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#17191d' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#d1d5db' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#464036' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#7a5b18' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#231f14' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#fde68a' }] },
  { featureType: 'road.local', elementType: 'labels.text.fill', stylers: [{ color: '#aeb6bf' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#303845' }] },
  { featureType: 'transit.station', elementType: 'labels.text.fill', stylers: [{ color: '#9ca3af' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#12334a' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#9cc8df' }] },
]
